<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\afh11-203v2.pdf" />
    <None Remove="Data\afh15-101.pdf" />
    <None Remove="Data\afh15-158.pdf" />
    <None Remove="Data\afi15-128.pdf" />
    <None Remove="Data\afman15-111.pdf" />
    <None Remove="Data\afman15-124.pdf" />
    <None Remove="Data\dafi15-129.pdf" />
    <None Remove="Data\dafpd15-1.pdf" />
    <None Remove="Models\bge-base-en-v1.5-q4_k_m.gguf" />
    <None Remove="Models\qwen2.5-coder-7b-instruct-q4_k_m.gguf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\afh11-203v2.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\afh15-101.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\afh15-158.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\afi15-128.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\afman15-111.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\afman15-124.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\dafi15-129.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\dafpd15-1.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AiModels\bge-base-en-v1.5-q4_k_m.gguf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AiModels\qwen2.5-coder-7b-instruct-q4_k_m.gguf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LLamaSharp" Version="0.26.0" />
    <PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.26.0" />
    <PackageReference Include="LLamaSharp.Backend.Vulkan" Version="0.26.0" />
    <PackageReference Include="LLamaSharp.Backend.Vulkan.Windows" Version="0.26.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.6" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
  </ItemGroup>

</Project>
